# Generated by Django 4.1.6 on 2023-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(blank=True, choices=[('Recruiter', 'Recruiter'), ('Collaborator', 'Collaborator'), ('Hiring Manager', 'Hiring Manager')], max_length=255, null=True),
        ),
    ]
