# Generated by Django 4.1.6 on 2023-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='org/profile/offer/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(blank=True, choices=[('Hiring Manager', 'Hiring Manager'), ('Recruiter', 'Recruiter'), ('Collaborator', 'Collaborator')], max_length=255, null=True),
        ),
    ]
