# Generated by Django 4.1.6 on 2023-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='ogr',
            new_name='org',
        ),
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(blank=True, choices=[('Hiring Manager', 'Hiring Manager'), ('Collaborator', 'Collaborator'), ('Recruiter', 'Recruiter')], max_length=255, null=True),
        ),
    ]
