# Generated by Django 4.1.6 on 2023-05-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_rename_ogr_activitylog_org_alter_organization_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='activity_type',
            new_name='aname',
        ),
    ]
