# Generated by Django 4.1.6 on 2023-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_notification_arefid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='adminRead',
            field=models.BooleanField(default='False'),
        ),
    ]
