# Generated by Django 4.1.6 on 2023-05-08 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='candidate', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('erefid', models.SlugField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Candidate Account',
                'verbose_name_plural': 'Candidates Account',
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
                ('yearofjoin', models.DateField(blank=True, null=True)),
                ('yearofend', models.DateField(blank=True, null=True)),
                ('edubody', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Education',
                'verbose_name_plural': 'Candidate Educations',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('year_of_join', models.DateField(blank=True, null=True)),
                ('year_of_end', models.DateField(blank=True, null=True)),
                ('expbody', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Experience',
                'verbose_name_plural': 'Candidate Experiences',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('profile', models.FileField(default='default_image.jpeg', upload_to='candidate/logo/name/')),
                ('summary', models.CharField(blank=True, max_length=256, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=256, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=256, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=256, null=True)),
                ('recuriter_message', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('yearofissue', models.DateField(blank=True, null=True)),
                ('yearofexp', models.DateField(blank=True, null=True)),
                ('creid', models.CharField(blank=True, max_length=256, null=True)),
                ('creurl', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Certificate',
                'verbose_name_plural': 'Candidate Certificate',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Social Link',
                'verbose_name_plural': 'Candidate Social Links',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='candidate/resume/')),
                ('file_img', models.FileField(blank=True, null=True, upload_to='candidate/resume/png/')),
                ('full_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Resume',
                'verbose_name_plural': 'Candidate Resumes',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('experties', models.CharField(blank=True, max_length=256, null=True)),
                ('skill_set', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Skill',
                'verbose_name_plural': 'Candidate Skills',
                'ordering': ('timestamp',),
            },
        ),
    ]
