# Generated by Django 4.1.6 on 2023-05-08 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrefid', models.SlugField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=256, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('agreement', models.FileField(blank=True, null=True, upload_to='vendor/agreement/')),
                ('agreement_valid_start_date', models.DateField(blank=True, null=True)),
                ('agreement_valid_end_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('onboard', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.superadmin')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vendors', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vendor_logo', models.FileField(blank=True, null=True, upload_to='vendor/logos/')),
                ('contact_2', models.CharField(blank=True, max_length=256, null=True)),
                ('license_number', models.CharField(blank=True, max_length=256, null=True)),
                ('headquater_address', models.TextField(blank=True, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='vendor/agreement/signature/')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.newvendor')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
