# Generated by Django 4.1.6 on 2023-05-08 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('organization', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arefid', models.SlugField(blank=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Application',
                'verbose_name_plural': 'Candidate Applications',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.SlugField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=300, null=True)),
                ('job_function', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
                ('group_or_division', models.CharField(blank=True, max_length=300, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('looking_for', models.TextField(blank=True, null=True)),
                ('jobSkill', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=300, null=True)),
                ('experience', models.CharField(blank=True, max_length=300, null=True)),
                ('education', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('currency', models.CharField(blank=True, max_length=300, null=True)),
                ('relocation', models.CharField(blank=True, max_length=300, null=True)),
                ('visa', models.CharField(blank=True, max_length=300, null=True)),
                ('worktype', models.CharField(blank=True, max_length=300, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('jobStatus', models.CharField(blank=True, max_length=300, null=True)),
                ('team', models.ManyToManyField(blank=True, related_name='Team', to='organization.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ManyToManyField(blank=True, related_name='Vendor', to='vendors.newvendor')),
            ],
            options={
                'verbose_name': 'Organization Job',
                'verbose_name_plural': 'Organization Jobs',
            },
        ),
        migrations.CreateModel(
            name='VendorCandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcrefid', models.SlugField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='vendor/candidate/resume/')),
                ('summary', models.CharField(blank=True, max_length=256, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=256, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=256, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=256, null=True)),
                ('recuriter_message', models.CharField(blank=True, max_length=256, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.newvendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorCandidateSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.vendorcandidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Social Link',
                'verbose_name_plural': 'Candidate Social Links',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='VendorCandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('year_of_join', models.DateField(blank=True, null=True)),
                ('year_of_end', models.DateField(blank=True, null=True)),
                ('expbody', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.vendorcandidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Experience',
                'verbose_name_plural': 'Candidate Experiences',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='VendorCandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
                ('yearofjoin', models.DateField(blank=True, null=True)),
                ('yearofend', models.DateField(blank=True, null=True)),
                ('edubody', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.vendorcandidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Education',
                'verbose_name_plural': 'Candidate Educations',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='VendorCandidateCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('yearofissue', models.DateField(blank=True, null=True)),
                ('yearofexp', models.DateField(blank=True, null=True)),
                ('creid', models.CharField(blank=True, max_length=256, null=True)),
                ('creurl', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.vendorcandidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Certificate',
                'verbose_name_plural': 'Candidate Certificate',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='VendorApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arefid', models.SlugField(blank=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.vendorcandidateprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.newvendor')),
            ],
            options={
                'verbose_name': 'Vendors Application',
                'verbose_name_plural': 'Vendors Applications',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.applicant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Application Feedback',
                'verbose_name_plural': 'Candidate Application Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
    ]
