# Generated by Django 4.1.6 on 2023-05-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcandidatecertificate',
            options={'ordering': ('timestamp',), 'verbose_name': 'Vendor Candidate Certificate', 'verbose_name_plural': 'Vendor Candidate Certificate'},
        ),
        migrations.AlterModelOptions(
            name='vendorcandidateeducation',
            options={'ordering': ('timestamp',), 'verbose_name': 'Vendor Candidate Education', 'verbose_name_plural': 'Vendor Candidate Educations'},
        ),
        migrations.AlterModelOptions(
            name='vendorcandidateexperience',
            options={'ordering': ('timestamp',), 'verbose_name': 'Vendor Candidate Experience', 'verbose_name_plural': 'Vendor Candidate Experiences'},
        ),
        migrations.AlterModelOptions(
            name='vendorcandidatesociallink',
            options={'ordering': ('timestamp',), 'verbose_name': 'Vendor Candidate Social Link', 'verbose_name_plural': 'Vendor Candidate Social Links'},
        ),
        migrations.AlterField(
            model_name='vendorapplicant',
            name='applicant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.vendorcandidateprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorapplicant',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorapplicant',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vendors.newvendor'),
            preserve_default=False,
        ),
    ]
