# Generated by Django 4.1.6 on 2023-05-16 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_alter_vendorcandidatecertificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, max_length=1000, null=True)),
                ('section', models.CharField(blank=True, max_length=1000, null=True)),
                ('divsion', models.CharField(blank=True, max_length=1000, null=True)),
                ('grade', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('currency', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary_from', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary_to', models.CharField(blank=True, max_length=1000, null=True)),
                ('candidate_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('visa_sponsorship', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid_relocation', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicant')),
                ('approval_authorities', models.ManyToManyField(blank=True, related_name='Authority', to='organization.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.offermanagement')),
            ],
        ),
    ]
