# Generated by Django 4.1.6 on 2023-05-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_offermanagement_offerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermanagement',
            name='omrefid',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
