# Generated by Django 4.1.6 on 2023-05-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_role'),
        ('job', '0004_offermanagement_omrefid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerfeedback',
            name='ofrefid',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerfeedback',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
