# Generated by Django 4.1.6 on 2023-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_offerfeedback_organization_candidateinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermanagement',
            name='offerLetter',
            field=models.FileField(blank=True, null=True, upload_to='org/candidate/offer/'),
        ),
    ]
