# Generated by Django 4.1.6 on 2023-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_offermanagement_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermanagement',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
