# Generated by Django 4.1.6 on 2023-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_offermanagement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinterview',
            name='date_time',
        ),
        migrations.AddField(
            model_name='candidateinterview',
            name='date_time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateinterview',
            name='date_time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
