# Generated by Django 4.1.6 on 2023-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_candidateinterview_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermanagement',
            name='candidate_status',
            field=models.CharField(default='Pending', max_length=300),
        ),
    ]
