# Generated by Django 4.1.6 on 2023-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_organization_role'),
        ('job', '0010_offermanagement_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinterview',
            name='irefid',
            field=models.SlugField(blank=True),
        ),
        migrations.RemoveField(
            model_name='candidateinterview',
            name='add_interviewer',
        ),
        migrations.AddField(
            model_name='candidateinterview',
            name='add_interviewer',
            field=models.ManyToManyField(blank=True, related_name='Interviewer', to='organization.organization'),
        ),
    ]
