# Generated by Django 4.1.6 on 2023-05-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_organization_role'),
        ('job', '0011_candidateinterview_irefid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinterview',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationprofile'),
        ),
    ]
